---
  
- name: test template run
  hosts: 3.86.208.114
  user: ansadmin
  vars: 
    env: staging
    my_app_release: v1.1
  tasks:
    - name: copy the j2 template to the remote node
      template:
        src: "{{ item }}.j2"
        dest: "/home/ansadmin/{{ item }}"
#        user: ansadmin
#        group: ansadmin
        mode: 0600
      become: true
      loop:
        - ans-conf-file
        - ans-release-version