---

- name: Network Getting Started First Playbook
  hosts: web
  user:  ansadmin
  tasks:

    - name: ping test
      ping:

    - name: Display the config
      command: date

    - copy:
       src: /home/ansadmin/project1/inventory.txt
       dest: /home/ansadmin
       owner: ansadmin
       group: ansadmin
       mode: 0644

    - name: Upgrade all packages
      become: true
      become_method: sudo
      yum:
        name: '*'
        state: latest

    - name: Install the latest version of Apache
      become: true
      become_method: sudo
      yum:
        name: httpd
        state: latest

    - name: Uninstall the latest version of Apache
      become: true
      become_method: sudo
      yum:
        name: httpd
        state: absent

    - name: Install the latest version of nginx
      become: true
      become_method: sudo
      yum:
        name: nginx
        state: latest

    - name: Nnginx service start
      service:
        name: nginx
        state: started
      become: true
